#!/bin/sh

set -x

rm CONTRIBUTING.md
rm LICENSE.md
rm README.md
cp docs/CONTRIBUTING.md CONTRIBUTING.md
cp docs/LICENSE.md LICENSE.md
cp docs/index.md README.md

cat pre.md > book.md
cat docs/index.md >> book.md


mv book.md docs/
cd docs
pandoc book.md -o book.pdf
